# Generated by Django 5.1.6 on 2025-02-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_armado', models.DateField()),
                ('fecha_entregado', models.DateField()),
                ('extensor_rango', models.BooleanField(default=False)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
            ],
        ),
    ]
