# Generated by Django 5.1.6 on 2025-02-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='extensor_rango',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
