# Generated by Django 5.1.6 on 2025-03-07 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reporte_extensor_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('motor_num', models.CharField(max_length=255)),
                ('fecha_fabr', models.DateField()),
                ('peso', models.FloatField(editable=False)),
                ('voltaje', models.IntegerField(editable=False)),
                ('potencia', models.FloatField(editable=False)),
                ('motivo', models.TextField()),
                ('evaluacion', models.TextField()),
                ('trabajos_hechos', models.TextField()),
                ('piezas_usadas', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('nombre_especialista', models.CharField(max_length=50)),
                ('conformidad_cliente', models.BooleanField()),
                ('facturar_a', models.CharField(default='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reporte')),
            ],
        ),
    ]
