# Generated by Django 5.1.6 on 2025-08-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cambioaceitetriciclo_cliente_empresa_garantia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='llamada',
        ),
        migrations.AddField(
            model_name='registro',
            name='bandas_freno',
            field=models.BooleanField(default=False, verbose_name='Bandas de freno'),
        ),
        migrations.AddField(
            model_name='registro',
            name='baterias',
            field=models.BooleanField(default=False, verbose_name='Baterías'),
        ),
        migrations.AddField(
            model_name='registro',
            name='caja_luces',
            field=models.BooleanField(default=False, verbose_name='Caja luces'),
        ),
        migrations.AddField(
            model_name='registro',
            name='caja_reguladora',
            field=models.BooleanField(default=False, verbose_name='Caja reguladora'),
        ),
        migrations.AddField(
            model_name='registro',
            name='calso_extensor',
            field=models.BooleanField(default=False, verbose_name='Calso del extensor'),
        ),
        migrations.AddField(
            model_name='registro',
            name='cargador_bateria',
            field=models.BooleanField(default=False, verbose_name='Cargador de batería'),
        ),
        migrations.AddField(
            model_name='registro',
            name='claxon',
            field=models.BooleanField(default=False, verbose_name='Claxon'),
        ),
        migrations.AddField(
            model_name='registro',
            name='conmutadores',
            field=models.BooleanField(default=False, verbose_name='Conmutadores'),
        ),
        migrations.AddField(
            model_name='registro',
            name='diferencial',
            field=models.BooleanField(default=False, verbose_name='Diferencial'),
        ),
        migrations.AddField(
            model_name='registro',
            name='extensor_rango',
            field=models.BooleanField(default=False, verbose_name='Extensor de rango'),
        ),
        migrations.AddField(
            model_name='registro',
            name='fallo',
            field=models.BooleanField(default=False, verbose_name='Fallo'),
        ),
        migrations.AddField(
            model_name='registro',
            name='farol_delantero',
            field=models.BooleanField(default=False, verbose_name='Farol delantero'),
        ),
        migrations.AddField(
            model_name='registro',
            name='farol_trasero',
            field=models.BooleanField(default=False, verbose_name='Farol trasero'),
        ),
        migrations.AddField(
            model_name='registro',
            name='llave_combustible',
            field=models.BooleanField(default=False, verbose_name='Llave de combustible'),
        ),
        migrations.AddField(
            model_name='registro',
            name='motor_1000w',
            field=models.BooleanField(default=False, verbose_name='Motor de 1000w'),
        ),
        migrations.AddField(
            model_name='registro',
            name='motor_1200w',
            field=models.BooleanField(default=False, verbose_name='Motor 1200w'),
        ),
        migrations.AddField(
            model_name='registro',
            name='motor_1500w',
            field=models.BooleanField(default=False, verbose_name='Motor 1500w'),
        ),
        migrations.AddField(
            model_name='registro',
            name='otros',
            field=models.TextField(blank=True, help_text='Especifica cualquier problema no listado arriba', verbose_name='Otros (especificar)'),
        ),
        migrations.AddField(
            model_name='registro',
            name='panel_instrumentos',
            field=models.BooleanField(default=False, verbose_name='Panel de instrumentos'),
        ),
        migrations.AddField(
            model_name='registro',
            name='problema_electrico',
            field=models.BooleanField(default=False, verbose_name='Problema eléctrico'),
        ),
        migrations.AddField(
            model_name='registro',
            name='pulmon_stops',
            field=models.BooleanField(default=False, verbose_name='Pulmón de stops'),
        ),
        migrations.AddField(
            model_name='registro',
            name='rodamientos_delanteros',
            field=models.BooleanField(default=False, verbose_name='Rodamientos delanteros'),
        ),
        migrations.AddField(
            model_name='registro',
            name='rodamientos_direccion',
            field=models.BooleanField(default=False, verbose_name='Rodamientos dirección'),
        ),
        migrations.AddField(
            model_name='registro',
            name='rodamientos_traseros',
            field=models.BooleanField(default=False, verbose_name='Rodamientos traseros'),
        ),
        migrations.AddField(
            model_name='registro',
            name='tarjeta_extensor',
            field=models.BooleanField(default=False, verbose_name='Tarjeta del extensor'),
        ),
        migrations.AddField(
            model_name='registro',
            name='tubo_escape',
            field=models.BooleanField(default=False, verbose_name='Tubo de escape'),
        ),
    ]
