# Generated by Django 5.1.6 on 2025-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_registro_llamada_registro_bandas_freno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(verbose_name='Fecha entregado'),
        ),
    ]
