# Generated by Django 5.1.6 on 2025-08-12 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_registro_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='bandas_freno',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='baterias',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='caja_luces',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='caja_reguladora',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='calso_extensor',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cargador_bateria',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='claxon',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='conmutadores',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='diferencial',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='extensor_rango',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='fallo',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='farol_delantero',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='farol_trasero',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='llave_combustible',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='motor_1000w',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='motor_1200w',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='motor_1500w',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='panel_instrumentos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='problema_electrico',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='pulmon_stops',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='rodamientos_delanteros',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='rodamientos_direccion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='rodamientos_traseros',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='tarjeta_extensor',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='tubo_escape',
        ),
        migrations.AddField(
            model_name='garantia',
            name='bandas_freno',
            field=models.BooleanField(default=False, verbose_name='Bandas de freno'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='baterias',
            field=models.BooleanField(default=False, verbose_name='Baterías'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='caja_luces',
            field=models.BooleanField(default=False, verbose_name='Caja luces'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='caja_reguladora',
            field=models.BooleanField(default=False, verbose_name='Caja reguladora'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='cargador_bateria',
            field=models.BooleanField(default=False, verbose_name='Cargador de batería'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='diferencial',
            field=models.BooleanField(default=False, verbose_name='Diferencial'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='extensor_rango',
            field=models.BooleanField(default=False, verbose_name='Extensor de rango'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='farol_delantero',
            field=models.BooleanField(default=False, verbose_name='Farol delantero'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='farol_trasero',
            field=models.BooleanField(default=False, verbose_name='Farol trasero'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='motor_1000w',
            field=models.BooleanField(default=False, verbose_name='Motor de 1 000w'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='motor_1200w',
            field=models.BooleanField(default=False, verbose_name='Motor 1200w'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='motor_1500w',
            field=models.BooleanField(default=False, verbose_name='Motor 1 500w'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='otros',
            field=models.TextField(blank=True, help_text='Especifica otros problemas no listados', verbose_name='Otros'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='problema_electrico',
            field=models.BooleanField(default=False, verbose_name='Problema eléctrico'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='rodamientos_delanteros',
            field=models.BooleanField(default=False, verbose_name='Rodamientos delanteros'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='rodamientos_direccion',
            field=models.BooleanField(default=False, verbose_name='Rodamientos dirección'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='rodamientos_traseros',
            field=models.BooleanField(default=False, verbose_name='Rodamientos traseros'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='tarjeta',
            field=models.BooleanField(default=False, verbose_name='Tarjeta'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='tubo_escape',
            field=models.BooleanField(default=False, verbose_name='Tubo de escape'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 8, 12), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='otros',
            field=models.TextField(blank=True, help_text='Especifica problema', verbose_name='Motivo'),
        ),
    ]
