# Generated by Django 5.1.6 on 2025-03-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_garantia_peso_alter_garantia_potencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='sello',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
