# Generated by Django 5.1.6 on 2025-03-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reporte_sello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='carnet',
            field=models.CharField(max_length=50, verbose_name='Carnet/NIT'),
        ),
    ]
