# Generated by Django 5.1.6 on 2025-08-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_registro_bandas_freno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='piezas_usadas',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Lista de piezas usadas'),
        ),
    ]
