# Generated by Django 5.1.6 on 2025-08-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_garantia_piezas_usadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='otros',
            field=models.TextField(blank=True, help_text='Especifica otra pieza no listada', verbose_name='Otros'),
        ),
    ]
