# Generated by Django 5.1.6 on 2025-03-08 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reporte_carnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Clientes',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('carnet', models.CharField(max_length=50, verbose_name='Carnet/NIT')),
                ('direccion', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_armado', models.DateField()),
                ('fecha_entregado', models.DateField()),
                ('extensor_rango', models.CharField(max_length=255, unique=True)),
                ('sello', models.CharField(default='NONE', max_length=255)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('llamada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Clientes_Pendientes',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('carnet', models.CharField(blank=True, max_length=50, verbose_name='Carnet/NIT')),
                ('direccion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_armado', models.DateField()),
                ('fecha_entregado', models.DateField(blank=True)),
                ('extensor_rango', models.CharField(blank=True, max_length=255, unique=True)),
                ('sello', models.CharField(blank=True, max_length=255)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('autorizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='garantia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.registro_clientes'),
        ),
        migrations.DeleteModel(
            name='Reporte',
        ),
    ]
