# Generated by Django 5.1.6 on 2025-03-08 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_registro_clientes_registro_clientes_pendientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_clientes',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='carnet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Carnet/NIT'),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='extensor_rango',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='fecha_armado',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='fecha_entregado',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='sello',
            field=models.CharField(blank=True, default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='registro_clientes_pendientes',
            name='fecha_entregado',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
