# Generated by Django 5.1.6 on 2025-08-13 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_garantia_otros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 8, 13), verbose_name='Fecha de Emision'),
        ),
    ]
