# Generated by Django 5.1.6 on 2025-03-08 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_registro_clientes_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Empresa',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_armado', models.DateField(default=datetime.datetime.now)),
                ('fecha_entregado', models.DateField(default=datetime.datetime.now)),
                ('extensor_rango', models.CharField(blank=True, max_length=255)),
                ('sello', models.CharField(blank=True, default='NONE', max_length=255)),
                ('articulo', models.CharField(choices=[('power station', 'Power Station'), ('triciclo', 'Triciclo')], default='Triciclo', max_length=20)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('llamada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Empresa_Pendientes',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_armado', models.DateField()),
                ('fecha_entregado', models.DateField(blank=True, default=datetime.datetime.now)),
                ('extensor_rango', models.CharField(blank=True, max_length=255, unique=True)),
                ('sello', models.CharField(blank=True, max_length=255)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('articulo', models.CharField(choices=[('power station', 'Power Station'), ('triciclo', 'Triciclo')], default='Triciclo', max_length=20)),
                ('autorizado', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='registro_clientes',
            name='extensor_rango',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
