# Generated by Django 5.1.6 on 2025-08-14 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_garantia_p_fecha_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la venta de triciclo', null=True, upload_to='ventas/fotos/', verbose_name='Foto de la venta'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='video',
            field=models.FileField(blank=True, help_text='Video de la venta de triciclo', null=True, upload_to='ventas/videos/', verbose_name='Video de la venta'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 8, 14), verbose_name='Fecha de Emision'),
        ),
    ]
