# Generated by Django 5.1.6 on 2025-03-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_registro_empresa_registro_empresa_pendientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_empresa_pendientes',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
    ]
