# Generated by Django 5.1.6 on 2025-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_garantia_foto_garantia_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='num',
            field=models.CharField(help_text='Se genera automaticamente y es secuencial en el formato PS###/YYYY', max_length=255, primary_key=True, serialize=False, verbose_name='Numero de Garantia'),
        ),
        migrations.AlterField(
            model_name='panels',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='marca',
            field=models.CharField(default='Perro Rojo', help_text='Marca por defecto de las Power_Stations', max_length=255, verbose_name='Marca'),
        ),
    ]
