# Generated by Django 5.1.6 on 2025-03-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_registro_empresa_pendientes_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_empresa',
            name='sn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registro_empresa_pendientes',
            name='sn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
