# Generated by Django 5.1.6 on 2025-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_garantia_p_num_alter_panels_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='claxon',
            field=models.BooleanField(default=False, verbose_name='Claxon'),
        ),
    ]
