# Generated by Django 5.1.6 on 2025-03-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_registro_empresa_sn_registro_empresa_pendientes_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_empresa',
            name='sn',
        ),
        migrations.RemoveField(
            model_name='registro_empresa_pendientes',
            name='sn',
        ),
    ]
