# Generated by Django 5.1.6 on 2025-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_garantia_claxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ventas/videos/', verbose_name='Video'),
        ),
    ]
