# Generated by Django 5.1.6 on 2025-03-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_registro_empresa_sn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_empresa',
            name='vin',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='VIN-S/N'),
        ),
        migrations.AlterField(
            model_name='registro_empresa_pendientes',
            name='vin',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='VIN-S/N'),
        ),
    ]
