# Generated by Django 5.1.6 on 2025-08-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_garantia_foto_alter_garantia_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='garantia/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='garantia/videos/', verbose_name='Video'),
        ),
    ]
