# Generated by Django 5.1.6 on 2025-08-16 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_garantia_foto_alter_garantia_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='fecha_creacion',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 8, 16), verbose_name='Fecha de Emision'),
        ),
    ]
