# Generated by Django 5.1.6 on 2025-03-11 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_registro_empresa_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_clientes',
            name='fecha_entregado',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='registro_empresa',
            name='fecha_entregado',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
