# Generated by Django 5.1.6 on 2025-03-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_registro_clientes_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_clientes',
            name='fecha_entregado',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='registro_clientes_pendientes',
            name='extensor_rango',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_clientes_pendientes',
            name='fecha_entregado',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='registro_clientes_pendientes',
            name='sello',
            field=models.CharField(blank=True, default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_empresa',
            name='fecha_entregado',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='registro_empresa_pendientes',
            name='extensor_rango',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='registro_empresa_pendientes',
            name='fecha_entregado',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='registro_empresa_pendientes',
            name='sello',
            field=models.CharField(blank=True, default='NONE', max_length=255),
        ),
    ]
