# Generated by Django 5.1.6 on 2025-08-26 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_garantia_fecha_creacion_alter_garantia_p_fecha_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_v_garantia',
            field=models.DateField(blank=True, default=None, editable=False, null=True, verbose_name='Fecha de vencimiento de garantia'),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_garantia',
            field=models.IntegerField(blank=True, choices=[(362, '362 días'), (180, '180 días')], default=None, null=True, verbose_name='Tipo de garantia'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 8, 26), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempoR',
            field=models.IntegerField(editable=False, help_text='Deprecado en nuevos registros', verbose_name='Tiempo Restante'),
        ),
    ]
