# Generated by Django 5.1.6 on 2025-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_registro_fecha_v_garantia_registro_tipo_garantia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo_garantia',
            field=models.IntegerField(choices=[(362, '362 días'), (180, '180 días')], default=0, verbose_name='Tipo de garantia'),
        ),
    ]
