# Generated by Django 5.1.6 on 2025-03-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_registro_clientes_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_clientes',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_clientes_pendientes',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_empresa',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_empresa_pendientes',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
