# Generated by Django 5.1.6 on 2025-08-28 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_registro_tipo_garantia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 8, 28), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_garantia',
            field=models.IntegerField(choices=[(365, '1 año'), (180, '6 meses')], default=0, verbose_name='Tipo de garantia'),
        ),
    ]
