# Generated by Django 5.1.6 on 2025-03-13 01:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_registro_clientes_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('carnet', models.CharField(blank=True, max_length=50, verbose_name='Carnet/NIT')),
                ('direccion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Power_Station',
            fields=[
                ('sn', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='S/N')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_armado', models.DateField(default=datetime.datetime.now)),
                ('fecha_entregado', models.DateField(blank=True, null=True)),
                ('extensor_rango', models.CharField(blank=True, max_length=255)),
                ('sello', models.CharField(blank=True, default='NONE', max_length=255)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('llamada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa')),
                ('power_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.power_station')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_Pendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_armado', models.DateField()),
                ('fecha_entregado', models.DateField(blank=True, null=True)),
                ('extensor_rango', models.CharField(blank=True, max_length=255)),
                ('sello', models.CharField(blank=True, default='NONE', max_length=255)),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('autorizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Triciclo',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Vin')),
            ],
        ),
        migrations.DeleteModel(
            name='Registro_Clientes_Pendientes',
        ),
        migrations.DeleteModel(
            name='Registro_Empresa',
        ),
        migrations.DeleteModel(
            name='Registro_Empresa_Pendientes',
        ),
        migrations.AlterField(
            model_name='garantia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='registro',
            name='triciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.triciclo'),
        ),
        migrations.DeleteModel(
            name='Registro_Clientes',
        ),
    ]
