# Generated by Django 5.1.6 on 2025-03-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cliente_empresa_power_station_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre_empresa',
            new_name='nombre',
        ),
    ]
