# Generated by Django 5.1.6 on 2025-08-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_garantia_p_fecha_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='evaluacion',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Evaluacion resumen'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='motivo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='recomendaciones',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Algunas recomendaciones'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='trabajos_hechos',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Trabajos realizados'),
        ),
    ]
