# Generated by Django 5.1.6 on 2025-10-20 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_garantia_evaluacion_alter_garantia_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='carnet',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Carnet'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 10, 20), verbose_name='Fecha de Emision'),
        ),
    ]
