# Generated by Django 5.1.6 on 2025-03-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_nombre_empresa_empresa_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_pendiente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='registro_pendiente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa'),
        ),
        migrations.AddField(
            model_name='registro_pendiente',
            name='power_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.power_station'),
        ),
        migrations.AddField(
            model_name='registro_pendiente',
            name='triciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.triciclo'),
        ),
    ]
