# Generated by Django 5.1.6 on 2025-03-14 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_registro_pendiente_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='fecha_armado',
        ),
        migrations.RemoveField(
            model_name='registro_pendiente',
            name='fecha_armado',
        ),
        migrations.AddField(
            model_name='power_station',
            name='fecha_armado',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='fecha_armado',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
