# Generated by Django 5.1.6 on 2025-11-18 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cliente_carnet_alter_garantia_p_fecha_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 11, 18), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='dist',
            field=models.CharField(choices=[('donki', 'Donki'), ('fueta', 'Fueta'), ('mkl', 'MKL'), ('slf', 'Solifoam')], max_length=255, verbose_name='Ditribuidora/Tienda'),
        ),
    ]
