# Generated by Django 5.1.6 on 2025-03-20 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_registro_fecha_armado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triciclo_Pendiente',
            fields=[
                ('vin', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Vin')),
                ('fecha_armado', models.DateField(default=datetime.datetime.now)),
                ('num_m', models.CharField(blank=True, max_length=255, verbose_name='Numero de Motor')),
                ('modelo', models.CharField(blank=True, max_length=255)),
                ('autorizado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='triciclo',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='num_m',
            field=models.CharField(blank=True, max_length=255, verbose_name='Numero de Motor'),
        ),
    ]
