# Generated by Django 5.1.6 on 2026-01-10 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_garantia_p_fecha_em_alter_power_station_dist'),
    ]

    operations = [
        migrations.AddField(
            model_name='triciclo',
            name='bateria_capacidad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batería Capacidad'),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='bateria_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batería ID'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2026, 1, 10), verbose_name='Fecha de Emision'),
        ),
    ]
