# Generated by Django 5.1.6 on 2025-03-20 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_triciclo_pendiente_triciclo_modelo_triciclo_num_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='tiempoR',
            field=models.IntegerField(default=180, editable=False, verbose_name='Tiempo Restante'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 3, 20)),
        ),
    ]
