# Generated by Django 5.1.6 on 2026-01-24 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_triciclo_bateria_capacidad_triciclo_bateria_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triciclo',
            name='bateria_fecha_fabricacion',
            field=models.DateField(blank=True, null=True, verbose_name='Bateria Fecha de Fabricación'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2026, 1, 24), verbose_name='Fecha de Emision'),
        ),
    ]
