# Generated by Django 5.1.6 on 2025-03-20 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_registro_tiempor_alter_registro_fecha_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 3, 20), verbose_name='Puesta en marcha'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='llamada',
            field=models.BooleanField(default=False, verbose_name='Reporte a Abraham por correo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tiempoR',
            field=models.IntegerField(editable=False, verbose_name='Tiempo Restante'),
        ),
        migrations.DeleteModel(
            name='Registro_Pendiente',
        ),
    ]
