# Generated by Django 5.1.6 on 2026-02-14 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_triciclo_bateria_fecha_fabricacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='pantalla',
            field=models.BooleanField(default=False, verbose_name='Pantalla'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2026, 2, 14), verbose_name='Fecha de Emision'),
        ),
    ]
