# Generated by Django 5.1.6 on 2026-05-04 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_garantia_pantalla_alter_garantia_p_fecha_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2026, 5, 4), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='dist',
            field=models.CharField(choices=[('donki', 'Donki'), ('fueta', 'Fueta'), ('mkl', 'MKL'), ('slf', 'Solifoam'), ('crd', 'Construcciones Reyna & Delgado')], max_length=255, verbose_name='Ditribuidora/Tienda'),
        ),
    ]
