# Generated by Django 5.1.6 on 2025-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_registro_fecha_entregado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Registro de cliente', 'verbose_name_plural': 'Registros de cliente'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Registro de MIPYME', 'verbose_name_plural': 'Registros de MIPYME'},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'verbose_name': 'Relacion de venta', 'verbose_name_plural': 'Relacion de ventas'},
        ),
        migrations.AlterModelOptions(
            name='triciclo',
            options={'verbose_name': 'Triciclo Armado', 'verbose_name_plural': 'Triciclos Armados'},
        ),
        migrations.AlterModelOptions(
            name='triciclo_pendiente',
            options={'verbose_name': 'Triciclo con puesta en marcha', 'verbose_name_plural': 'Triciclos con puesta en marcha'},
        ),
        migrations.RenameField(
            model_name='triciclo',
            old_name='modelo',
            new_name='extensor_rango',
        ),
        migrations.RenameField(
            model_name='triciclo_pendiente',
            old_name='modelo',
            new_name='extensor_rango',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='extensor_rango',
        ),
    ]
