# Generated by Django 5.1.6 on 2025-03-21 09:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_cliente_options_alter_empresa_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Triciclo_Pendiente',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Registro de T.C.P/P.N', 'verbose_name_plural': 'Registros de T.C.P/P.N'},
        ),
        migrations.AlterModelOptions(
            name='garantia',
            options={'verbose_name': 'Reporte de Reclamacion', 'verbose_name_plural': 'Reporte de Reclamaciones'},
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='fecha_fabr',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='motor_num',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='potencia',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='vin',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='voltaje',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='sello',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nit',
            field=models.CharField(blank=True, max_length=255, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='power_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.power_station'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='triciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.triciclo'),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='fecha_autorizado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='sello',
            field=models.CharField(blank=True, default='NONE', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='carnet',
            field=models.CharField(blank=True, max_length=50, verbose_name='Carnet'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='conformidad_cliente',
            field=models.BooleanField(verbose_name='Conformidad del cliente'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='evaluacion',
            field=models.TextField(max_length=255, verbose_name='Evaluacion resumen'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='facturar_a',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor')], max_length=255, verbose_name='Facturar a'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='motivo',
            field=models.TextField(max_length=255, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='nombre_especialista',
            field=models.CharField(choices=[('abraham pino valdes', 'Abraham Pino Valdes'), ('juan', 'Juan'), ('jose', 'Jose'), ('ailet', 'Ailet'), ('tamara', 'Tamara'), ('dago', 'Dago'), ('roberto', 'Roberto')], max_length=255, verbose_name='Especialista encargado'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='piezas_usadas',
            field=models.TextField(max_length=255, verbose_name='Lista de piezas usadas'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='recomendaciones',
            field=models.TextField(max_length=255, verbose_name='Algunas recomendaciones'),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='trabajos_hechos',
            field=models.TextField(max_length=255, verbose_name='Trabajos realizados'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 3, 21), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='llamada',
            field=models.TextField(blank=True, verbose_name='Reportar por correo(Especificar motivo)'),
        ),
    ]
