# Generated by Django 5.1.6 on 2025-03-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_triciclo_pendiente_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
