# Generated by Django 5.1.6 on 2025-04-02 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_garantia_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='receptor',
            field=models.CharField(blank=True, choices=[('tallerjireh47@gmail.com', 'Todos'), ('correo1@example.com', 'Correo 1'), ('correo2@example.com', 'Correo 2'), ('correo3@example.com', 'Correo 3')], help_text='Selecciona uno o varios receptores separados por comas', max_length=255, verbose_name='Receptor(es) del correo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 2), verbose_name='Fecha entregado'),
        ),
    ]
