# Generated by Django 5.1.6 on 2025-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_registro_receptor_alter_registro_fecha_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='receptor',
            field=models.CharField(blank=True, help_text='Selecciona uno o varios receptores', max_length=255, verbose_name='Receptor(es) del correo'),
        ),
    ]
