# Generated by Django 5.1.6 on 2025-04-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_registro_receptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantia',
            name='facturar_a',
        ),
        migrations.AddField(
            model_name='power_station',
            name='bases',
            field=models.IntegerField(default=3, editable=False, verbose_name='Bases'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='expansiones',
            field=models.IntegerField(default=3, editable=False, verbose_name='Expansiones'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='paneles',
            field=models.IntegerField(default=3, editable=False, verbose_name='Paneles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='tipo',
            field=models.CharField(choices=[('1era', '1era'), ('2da', '2da'), ('3ero', '3ero'), ('4ta', '4ta'), ('5ta', '5ta')], default=3, max_length=10, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='w',
            field=models.IntegerField(default=4, editable=False, verbose_name='W'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='power_station',
            name='sn',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
