# Generated by Django 5.1.6 on 2025-04-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_garantia_facturar_a_power_station_bases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power_station',
            name='tipo',
            field=models.CharField(choices=[('1-300w', '1-300W'), ('2-600w', '2-600W'), ('3-1200w', '3-1200W'), ('4-2400w', '4-2400W'), ('5-3000w', '5-3000W')], max_length=10, verbose_name='Tipo'),
        ),
    ]
