# Generated by Django 5.1.6 on 2025-04-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_power_station_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.CharField(max_length=255, verbose_name='Kit de Montaje')),
                ('cuchilla', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automatica')], max_length=255, verbose_name='Cuchilla')),
                ('act', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automatica')], max_length=255, verbose_name='Actualizacion de Software')),
            ],
            options={
                'verbose_name': 'Panel Solar',
                'verbose_name_plural': 'Paneles Solares',
            },
        ),
        migrations.AlterField(
            model_name='power_station',
            name='bases',
            field=models.IntegerField(editable=False, verbose_name='Bases de Paneles'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='w',
            field=models.IntegerField(editable=False, verbose_name='Watts'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.panels'),
        ),
        migrations.AddField(
            model_name='registro',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.panels'),
        ),
    ]
