# Generated by Django 5.1.6 on 2025-04-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_panels_alter_power_station_bases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panels',
            name='act',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=255, verbose_name='Actualizacion de Software'),
        ),
    ]
