# Generated by Django 5.1.6 on 2025-04-03 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_panels_act'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='aut',
            field=models.BooleanField(default=False, verbose_name='Kit Autorizado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 3), verbose_name='Fecha entregado'),
        ),
    ]
