# Generated by Django 5.1.6 on 2025-04-03 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_panels_aut_alter_registro_fecha_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='receptor',
            field=models.CharField(blank=True, help_text='Selecciona uno o varios receptores, o Todos', max_length=255, verbose_name='Receptor(es) del correo'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='autorizado',
            field=models.BooleanField(default=False, help_text='El triciclo se autorizara solo por el encargado de ello'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='fecha_armado',
            field=models.DateField(default=datetime.datetime.now, help_text='Fecha en que se armo el triciclo'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='fecha_autorizado',
            field=models.DateField(blank=True, help_text='Aparecera automaticamente al autorizar el triciclo', null=True),
        ),
    ]
