# Generated by Django 5.1.6 on 2025-04-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_panels_aut_alter_registro_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantia',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='panel',
        ),
    ]
