# Generated by Django 5.1.6 on 2025-04-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_garantia_panel_remove_registro_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStationPanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.panels')),
                ('power_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.power_station')),
            ],
        ),
    ]
