# Generated by Django 5.1.6 on 2025-04-03 09:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_powerstationpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='panels',
            name='num',
            field=models.CharField(default=2, max_length=255, verbose_name='Numero de Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='dist',
            field=models.CharField(default=4, max_length=255, verbose_name='Ditribuidora/Tienda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='marca',
            field=models.CharField(default='Perro Rojo', help_text='Marca por defecto de los paneles', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='power_station',
            name='modelo',
            field=models.CharField(default=12, max_length=255, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='power_station',
            name='fecha_armado',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Compra'),
        ),
        migrations.CreateModel(
            name='Garantia_P',
            fields=[
                ('num', models.IntegerField(help_text='Se genera automaticamente y es secuencial', primary_key=True, serialize=False, verbose_name='Numero de Garantia')),
                ('fecha_em', models.DateField(default=datetime.date(2025, 4, 3), verbose_name='Fecha de Emision')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa')),
                ('power_station', models.ForeignKey(blank=True, help_text='Aca estaran los datos especificos de la Power Station y sus paneles asociados, acceder para ver detalles.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.power_station')),
            ],
            options={
                'verbose_name': 'Registro de Garantia',
                'verbose_name_plural': 'Registros de Garantia',
            },
        ),
    ]
