# Generated by Django 5.1.6 on 2025-04-04 17:36

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_panels_num_power_station_dist_power_station_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia_p',
            name='condiciones_generales',
            field=models.TextField(default='- La estación de energía incluye una garantía de 1 año contra defectos de fabricación.\n- El panel solar incluye una garantía de 2 años y cubre defectos de fabricación.\n- La garantía del generador solar no cubre daños por uso inadecuado, accidentes o modificaciones no autorizadas.\n- Si el producto se usa de manera incorrecta o no según las instrucciones del fabricante, la garantía no cubrirá los daños resultantes.', help_text='Condiciones generales de la garantía por defecto', verbose_name='Condiciones Generales de Garantía'),
        ),
        migrations.AddField(
            model_name='garantia_p',
            name='condiciones_reparacion',
            field=models.TextField(default='Cuando surjan problemas comunes como:\n- Fallos en la batería (pérdida de capacidad, incapacidad de cargarse).\n- Problemas con los puertos de salida (USB, CA, DC).\n- Errores en la pantalla LCD o interfaz de usuario.\n- Fallos en el sistema de gestión de energía (sobrecalentamiento, cortocircuitos).\n\nEl técnico autorizado evaluará el problema y determinará si está cubierto por la garantía.', help_text='Condiciones y procedimientos para reparaciones cubiertas por garantía', verbose_name='Condiciones de Reparación'),
        ),
        migrations.AddField(
            model_name='garantia_p',
            name='condiciones_sustitucion',
            field=models.TextField(default='Situaciones que justifican la sustitución:\n- El problema no puede repararse de manera económica o efectiva.\n- El dispositivo tiene un defecto de fábrica grave.\n- Todo ello será avalado por el fabricante.', help_text='Condiciones bajo las cuales se reemplazará el producto', verbose_name='Condiciones de Sustitución'),
        ),
        migrations.AddField(
            model_name='garantia_p',
            name='exclusiones_garantia',
            field=models.TextField(default='- Daños por uso incorrecto o negligencia.\n- Modificaciones o reparaciones no autorizadas.\n- Desgaste normal de la batería.\n- Daños por factores externos (sobretensiones, rayos, inundaciones, etc.).\n- Uso en condiciones extremas fuera de los rangos especificados.\n- Falta de mantenimiento según instrucciones del fabricante.\n- Consumibles o accesorios (cables, adaptadores).\n- Daños por software no autorizado.\n- Daños cosméticos (arañazos, abolladuras) que no afectan el funcionamiento.', help_text='Lista de situaciones que no están cubiertas por la garantía', verbose_name='Exclusiones de la Garantía'),
        ),
        migrations.AddField(
            model_name='garantia_p',
            name='politicas_costos',
            field=models.TextField(default='- Cubierto por la garantía: Reparación o sustitución gratuita.\n- No cubierto por la garantía: Cliente paga costos de reparación/sustitución.\n- En caso de defecto de fabricación cubierto, nos comprometemos a reparar o reemplazar su estación de energía.', help_text='Políticas sobre costos de reparación y sustitución', verbose_name='Políticas de Costos'),
        ),
        migrations.AddField(
            model_name='garantia_p',
            name='procedimiento_reclamo',
            field=models.TextField(default='1. Contacto: Llamar a Tamara Reinosa Ferrer (asistencia técnica y garantía Fueta International) al celular 59423597 o escribir por WhatsApp al mismo número.\n2. Revisión: Presentar la factura de compra y modelo de garantía.\n3. Evaluación: El equipo técnico determinará si aplica la garantía.\n4. Solución: Se procederá con la reparación, reemplazo o reembolso según corresponda.', help_text='Pasos a seguir para hacer un reclamo de garantía', verbose_name='Procedimiento para Reclamo'),
        ),
        migrations.AddField(
            model_name='power_station',
            name='num',
            field=models.UUIDField(default=uuid.uuid4, help_text='Identificador único generado automáticamente', verbose_name='Numero de Serie'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 4, 4), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='panels',
            name='num',
            field=models.CharField(default=uuid.uuid4, max_length=255, verbose_name='Numero de Serie'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='marca',
            field=models.CharField(default='Perro Rojo', help_text='Marca por defecto de las Power_Stations', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='modelo',
            field=models.CharField(default='Longi', help_text='Modelo por defecto de las Power_Stations', max_length=255, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='w',
            field=models.IntegerField(editable=False, verbose_name='Potencia/Capacidad(Watts)'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 4), verbose_name='Fecha entregado'),
        ),
    ]
