# Generated by Django 5.1.6 on 2025-04-10 19:42

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_garantia_p_condiciones_generales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='power_station',
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 4, 10), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='num',
            field=models.CharField(default=uuid.uuid4, help_text='Identificador único generado automáticamente', verbose_name='Numero de Serie'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 10), verbose_name='Fecha entregado'),
        ),
        migrations.CreateModel(
            name='Registro_ps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entregado', models.DateField(default=datetime.date(2025, 4, 10), verbose_name='Fecha entregado')),
                ('tiempoR', models.IntegerField(editable=False, verbose_name='Tiempo Restante')),
                ('numero_reporte', models.IntegerField(editable=False, unique=True)),
                ('llamada', models.TextField(blank=True, verbose_name='Reportar por correo(Especificar motivo)')),
                ('receptor', models.CharField(blank=True, help_text='Selecciona uno o varios receptores, o Todos', max_length=255, verbose_name='Receptor(es) del correo')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente a ser Reportado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa a ser Reportada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa')),
                ('power_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.power_station')),
            ],
            options={
                'verbose_name': 'Relacion de venta',
                'verbose_name_plural': 'Relacion de ventas',
            },
        ),
    ]
