# Generated by Django 5.1.6 on 2025-04-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_registro_power_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_ps',
            name='tiempoR_pan',
            field=models.IntegerField(default=720, editable=False, verbose_name='Tiempo Restante(Paneles)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='tiempoR',
            field=models.IntegerField(editable=False, verbose_name='Tiempo Restante(PowerStation)'),
        ),
    ]
