# Generated by Django 5.1.6 on 2025-04-18 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_registro_ps_tiempor_pan_alter_registro_ps_tiempor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power_station',
            name='num',
        ),
        migrations.AddField(
            model_name='power_station',
            name='nume',
            field=models.CharField(default=1, max_length=255, verbose_name='Numero de extensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power_station',
            name='vinch',
            field=models.CharField(default=1, max_length=255, verbose_name='Vin de chasis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 4, 18), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='tipo',
            field=models.CharField(choices=[('300w', '300W'), ('600w', '600W'), ('1200w', '1200W'), ('2400w', '2400W'), ('3000w', '3000W')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 18), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 18), verbose_name='Fecha entregado'),
        ),
    ]
