# Generated by Django 5.1.6 on 2025-04-19 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_power_station_num_power_station_nume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='power_station',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='power_station',
            name='vinch',
        ),
        migrations.AddField(
            model_name='triciclo',
            name='nume',
            field=models.CharField(default=1, max_length=255, verbose_name='Numero de extensor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triciclo',
            name='vinch',
            field=models.CharField(default=1, max_length=255, verbose_name='Vin de chasis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 4, 19), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 19), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 19), verbose_name='Fecha entregado'),
        ),
    ]
