# Generated by Django 5.1.6 on 2025-04-24 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_power_station_nume_remove_power_station_vinch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triciclo',
            name='obser',
            field=models.TextField(default=1, help_text='Algunas observaciones sobre el triciclo que pueden ser modificadas a lo largo del tiempo', verbose_name='Observaciones adicionales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 4, 24), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 24), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 4, 24), verbose_name='Fecha entregado'),
        ),
    ]
