# Generated by Django 5.1.6 on 2025-05-04 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_triciclo_obser_alter_garantia_p_fecha_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triciclo',
            name='nume',
        ),
        migrations.RemoveField(
            model_name='triciclo',
            name='vinch',
        ),
        migrations.AddField(
            model_name='triciclo',
            name='modelo',
            field=models.CharField(choices=[('Triciclo con Extensor de Rango', 'triciclo con extesnor de rango'), ('Triciclo Electrico de Carga', 'triciclo electrico de carga'), ('Triciclo Electrico con Panel Solar', 'triciclo electrico con panel solar'), ('Moto RY', 'moto ry'), ('Cuatriciclo T90', 'cuatriciclo t90')], default=2, help_text='Modelo del Triciclo', max_length=255, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 5, 4), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='num',
            field=models.CharField(help_text='Se genera automaticamente y es secuencial en el formato PS###/YYYY', primary_key=True, serialize=False, verbose_name='Numero de Garantia'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 4), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 4), verbose_name='Fecha entregado'),
        ),
    ]
