# Generated by Django 5.1.6 on 2025-05-06 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_triciclo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='triciclo',
            name='fecha_v',
            field=models.DateField(blank=True, default=None, help_text='Al marcar como vendido un triciclo la fecha se actualiza', null=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='vendido',
            field=models.BooleanField(default=False, help_text='Cuando se venda un triciclo dejarlo plasmado aqui', verbose_name='Vendido'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 5, 5), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 5), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 5), verbose_name='Fecha entregado'),
        ),
    ]
