# Generated by Django 5.1.6 on 2025-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_garantia_p_fecha_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_station',
            name='fecha_v',
            field=models.DateField(blank=True, default=None, help_text='Al marcarse como vendida una power station la fecha se actualiza', null=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AddField(
            model_name='power_station',
            name='vendido',
            field=models.BooleanField(default=False, help_text='Cuando se realice una relacion de venta de power station se vera reflejado aqui', verbose_name='Vendido'),
        ),
    ]
