# Generated by Django 5.1.6 on 2025-05-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_power_station_fecha_v_power_station_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triciclo',
            name='fecha_v',
            field=models.DateField(blank=True, default=None, help_text='Al marcarse como vendido un triciclo la fecha se actualiza', null=True, verbose_name='Fecha de Venta'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='vendido',
            field=models.BooleanField(default=False, help_text='Cuando se realice una relacion de venta de triciclo se vera reflejado aqui', verbose_name='Vendido'),
        ),
    ]
