# Generated by Django 5.1.6 on 2025-05-13 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_triciclo_fecha_v_alter_triciclo_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 5, 13), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 13), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 13), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='modelo',
            field=models.CharField(choices=[('triciclo con extensor de rango', 'TRICICLO CON EXTENSOR DE RANGO'), ('triciclo eléctrico de carga', 'TRICICLO ELÉCTRICO DE CARGA'), ('triciclo eléctrico con panel solar', 'TRICICLO ELÉCTRICO CON PANEL SOLAR'), ('moto ry', 'MOTO RY'), ('cuatriciclo t90', 'CUATRICICLO T90'), ('dsl pro', 'DSL PRO'), ('jl', 'JL'), ('ware frame', 'WARE FRAME')], help_text='Modelo del Triciclo', max_length=255, verbose_name='Modelo'),
        ),
    ]
