# Generated by Django 5.1.6 on 2025-05-17 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_garantia_p_fecha_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_station',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la power station', null=True, upload_to='ventas/fotos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='power_station',
            name='video',
            field=models.FileField(blank=True, help_text='Video de la power station', null=True, upload_to='ventas/videos/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='registro',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la venta de triciclo', null=True, upload_to='ventas/fotos/', verbose_name='Foto de la venta'),
        ),
        migrations.AddField(
            model_name='registro',
            name='video',
            field=models.FileField(blank=True, help_text='Video de la venta de triciclo', null=True, upload_to='ventas/videos/', verbose_name='Video de la venta'),
        ),
        migrations.AddField(
            model_name='registro_ps',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto de la venta de power station', null=True, upload_to='ventas/fotos/', verbose_name='Foto de la venta'),
        ),
        migrations.AddField(
            model_name='registro_ps',
            name='video',
            field=models.FileField(blank=True, help_text='Video de la venta de power station', null=True, upload_to='ventas/videos/', verbose_name='Video de la venta'),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del triciclo armado', null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='triciclo',
            name='video',
            field=models.FileField(blank=True, help_text='Video del armado del triciclo', null=True, upload_to='videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 5, 17), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 17), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(default=datetime.date(2025, 5, 17), verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='modelo',
            field=models.CharField(choices=[('TY150UK', 'TY150UK'), ('triciclo eléctrico de carga HK', 'TRICICLO ELÉCTRICO DE CARGA HK'), ('triciclo eléctrico con panel solar HY', 'TRICICLO ELÉCTRICO CON PANEL SOLAR HY'), ('moto RY', 'MOTO RY'), ('CUATRICICLO T90', 'CUATRICICLO T90'), ('DSL PRO', 'DSL PRO'), ('JL', 'JL'), ('WARE FRAME', 'WARE FRAME')], help_text='Modelo del Triciclo', max_length=255, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='triciclo',
            name='sello',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
