# Generated by Django 5.1.6 on 2025-05-28 16:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_power_station_foto_power_station_video_registro_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 5, 28), verbose_name='Fecha de Emision'),
        ),
        migrations.AlterField(
            model_name='power_station',
            name='dist',
            field=models.CharField(choices=[('donki', 'Donki'), ('fueta', 'Fueta'), ('mkl', 'MKL')], max_length=255, verbose_name='Ditribuidora/Tienda'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha entregado'),
        ),
        migrations.AlterField(
            model_name='registro_ps',
            name='fecha_entregado',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha entregado'),
        ),
        migrations.CreateModel(
            name='CambioAceiteTriciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha del cambio de aceite')),
                ('kilometros', models.PositiveIntegerField(help_text='Kilometraje al momento del cambio', verbose_name='Kilómetros reales')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cambios_aceite/fotos/', verbose_name='Foto del kilometraje/cambio')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('no_paso_garantia', models.BooleanField(default=False, verbose_name='No pasó la garantía')),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cliente')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empresa')),
                ('triciclo', models.ForeignKey(help_text='Triciclo asociado al cambio de aceite', on_delete=django.db.models.deletion.CASCADE, to='app.triciclo')),
            ],
            options={
                'verbose_name': 'Cambio de aceite (triciclo)',
                'verbose_name_plural': 'Cambios de aceite (triciclos)',
            },
        ),
    ]
