# Generated by Django 5.1.6 on 2025-06-11 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_alter_garantia_p_fecha_em_alter_power_station_dist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 6, 10), verbose_name='Fecha de Emision'),
        ),
    ]
