# Generated by Django 5.1.6 on 2025-06-11 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_garantia_p_fecha_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioaceitetriciclo',
            name='km1000',
            field=models.BooleanField(default=False, help_text='¿Se realizó el cambio a los 1000 km?', verbose_name='1000 km'),
        ),
        migrations.AddField(
            model_name='cambioaceitetriciclo',
            name='km300',
            field=models.BooleanField(default=False, help_text='¿Se realizó el cambio a los 300 km?', verbose_name='300 km'),
        ),
        migrations.AddField(
            model_name='cambioaceitetriciclo',
            name='km500',
            field=models.BooleanField(default=False, help_text='¿Se realizó el cambio a los 500 km?', verbose_name='600 km'),
        ),
    ]
