# Generated by Django 5.1.6 on 2025-06-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_cambioaceitetriciclo_km1000_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambioaceitetriciclo',
            name='km500',
        ),
        migrations.AddField(
            model_name='cambioaceitetriciclo',
            name='km600',
            field=models.BooleanField(default=False, help_text='¿Se realizó el cambio a los 600 km?', verbose_name='600 km'),
        ),
    ]
