# Generated by Django 5.1.6 on 2025-06-11 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_remove_cambioaceitetriciclo_km500_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='power_station',
            name='dist_client',
            field=models.CharField(default='', max_length=255, verbose_name='Cliente de Distribuidora'),
        ),
        migrations.AlterField(
            model_name='garantia_p',
            name='fecha_em',
            field=models.DateField(default=datetime.date(2025, 6, 11), verbose_name='Fecha de Emision'),
        ),
    ]
